---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation template to provision a stack that detects and notifies about root user usage.

Parameters:
  EmailAddress:
    Type: String
    AllowedPattern: "^[\\x20-\\x45]?[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"
    ConstraintDescription: Email address required.
    Description: Enter an email address you want to subscribe to the Amazon SNS topic.

Resources:
  # EventBridge rule that captures:
  # Console sign in and API calls tracked via CloudTrail from the root user.
  RootUsageEventRule:
    Type: AWS::Events::Rule
    Properties: 
      Name: root-user-usage-events
      Description: Rule that captures console sign in and API calls from the root user.
      EventPattern:
        detail-type:
        - AWS API Call via CloudTrail
        - AWS Console Sign In via CloudTrail
        detail:
          userIdentity:
            type:
            - Root
      Targets: 
      - Id: root-user-usage-events-rule
        Arn: !Ref SnsTopic
    DependsOn:
    - SnsTopic

  # SNS Topic with Email subscription 
  # Note: Subscription must be confirmed prior to deploying the stack).
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: root-user-usage-events
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email-json

  # Allow EventBridge to invoke SNS
  EventBridgeToToSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: !Ref SnsTopic
      Topics: 
        - !Ref SnsTopic
    DependsOn:
    - SnsTopic
